
project_name: "mimic_medbert_poc"

data:
  admissions_path: "data/mimic-iv-clinical-databese-demo-2.2/hosp/admissions.csv.gz"
  diagnoses_path: "data/mimic-iv-clinical-databese-demo-2.2/hosp/diagnoses_icd.csv.gz"
  patients_path: "data/mimic-iv-clinical-databese-demo-2.2/hosp/patients.csv.gz"
  text_column: "icd_code"
  label_column: "diagnosis_group"
  test_size: 0.2
  random_seed: 1

model:
  pretrained_name: "emilyalsentzer/Bio_ClinicalBERT"
  max_length: 64
  num_train_epochs: 2
  batch_size: 8
  learning_rate: 3e-5
  weight_decay: 0.01

output:
  model_dir: "./models/medbert_poc"
  results_dir: "./results/"